# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as the base image
FROM node:18-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's source code
COPY src ./src
COPY tsconfig.json ./

# Build the TypeScript code
RUN npm run build

# Production image to run the application
FROM node:18-alpine AS production

# Set the working directory
WORKDIR /app

# Copy the build output and package.json files from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json /app/package-lock.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Environment variable for OAuth token
ENV MIRO_OAUTH_KEY=<YOUR_MIRO_OAUTH_KEY>

# Run the server
ENTRYPOINT ["node", "build/index.js", "--token", "MIRO-OAUTH-KEY"]